# Generated by Django 4.0.2 on 2022-02-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenants',
            name='Con_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenants',
            name='Con_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
