# Generated by Django 4.0.2 on 2022-02-25 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tenants', '0003_visitor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('Mobile', models.IntegerField()),
                ('Text', models.TextField()),
                ('Date_Reg', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
